language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - rbx-19mode
  - jruby-19mode
  - jruby-head
  - 1.9.2
  - 1.9.3
gemfile:
  - .gemfiles/rails-3.0
  - .gemfiles/rails-3.1
  - .gemfiles/rails-3.2
notifications:
  recipients:
    - adam@29ways.co.cuk
